# Generated by Django 6.0.2 on 2026-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_alter_dispute_options_alter_dispute_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldispute',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
