# Generated by Django 6.0.2 on 2026-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_add_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='supabase_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldispute',
            name='supabase_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
