# Generated by Django 6.0.2 on 2026-03-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disputes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('evidence_paths', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disputes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('terms', models.TextField()),
                ('agreed_by_buyer', models.BooleanField(blank=True, null=True)),
                ('agreed_by_seller', models.BooleanField(blank=True, null=True)),
                ('terms_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmed', models.BooleanField(blank=True, null=True)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('seller_confirmed', models.BooleanField(blank=True, null=True)),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('funds_held', models.BooleanField(blank=True, null=True)),
                ('funds_released', models.BooleanField(blank=True, null=True)),
                ('funds_released_at', models.DateTimeField(blank=True, null=True)),
                ('release_triggered_by', models.TextField(blank=True, null=True)),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('auto_trigger_fired', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'escrow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KycDocuments',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('document_type', models.TextField()),
                ('storage_path', models.TextField()),
                ('status', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kyc_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.TextField(blank=True, null=True)),
                ('delivery_deadline', models.DateTimeField(blank=True, null=True)),
                ('payfast_payment_id', models.TextField(blank=True, null=True, unique=True)),
                ('payfast_token', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('full_name', models.TextField()),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('role', models.TextField()),
                ('national_id_number', models.TextField(blank=True, null=True, unique=True)),
                ('id_document_type', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(blank=True, null=True)),
                ('is_2fa_enabled', models.BooleanField(blank=True, null=True)),
                ('totp_secret', models.TextField(blank=True, null=True)),
                ('kyc_status', models.TextField(blank=True, null=True)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('face_scan_verified', models.BooleanField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
