# Generated by Django 6.0.2 on 2026-02-27 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('funded', 'Funded (Held in Escrow)'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('release_requested_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('seller_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payfast_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
