# Generated by Django 6.0.2 on 2026-03-13 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_payfast',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PayFast fee deducted', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_platform',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee deducted', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount buyer pays', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='net_to_seller',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount seller receives after all fees', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('funded', 'Funded (Held in Escrow)'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Fee Structure', max_length=100)),
                ('platform_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Platform fee percentage e.g. 5.00 for 5%', max_digits=5)),
                ('platform_fixed', models.DecimalField(decimal_places=2, default=2.0, help_text='Fixed platform fee in rands e.g. 2.00', max_digits=10)),
                ('payfast_percentage', models.DecimalField(decimal_places=2, default=3.5, help_text='PayFast fee percentage e.g. 3.50 for 3.5%', max_digits=5)),
                ('payfast_fixed', models.DecimalField(decimal_places=2, default=2.0, help_text='Fixed PayFast fee in rands e.g. 2.00', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only one config should be active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated this', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Fee Configuration',
                'verbose_name_plural': 'Platform Fee Configurations',
            },
        ),
    ]
